spring.data.rest.base-path: /data

gsync:

  syncmaster:
    svn:
      username: ${DEFAULT_SYNC_USER:syncmaster}
      password: ${DEFAULT_SYNC_PASSWORD:password}

  repo.path: ${REPO_PATH:/etc/gsync}

server:
  port: 9521